language: node_js

node_js:
  - 0.10

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

addons:
  sauce_connect: true

env:
  matrix:
    - BROWSER_NAME='firefox' BROWSER_VERSION='33' PLATFORM='Windows 7'
    - BROWSER_NAME='chrome' BROWSER_VERSION='33' PLATFORM='Windows 7'
    - BROWSER_NAME='chrome' BROWSER_VERSION='39' PLATFORM='OS X 10.9'

  global:
    - secure: FGht5/n4REl7xtxDCMmE7JEwR4wxRWFrRn+1rpHZ/e3mtgWwqGt2+IUOkonCpYprdzjO7o9MUCXP58kLKhq+9q1cdXMoawvwYfH0e0RTr6d1BdHj2DX4U6iTnuSnzZ7l8yheDUfoJnLX9ZETVSqzzxI8Ck96SjqYjcYRM4kvgEc=
    - secure: HaZoRLn88KojG0GEvkvFXBq4fvEkMcw5KJhkAvJKg1N7agrGuRfKbBmpQ9IFSMoyc6/ifcek0mkn2XsOlLJfGzGNxEzDL4LDYoMqWcAwSk16t5RCRRB4WAlKYIMuRC7uotHCxU2cikVzBFeMEGcQclot2E1oTiVjaQ6X233bEMU=

before_script:
  - npm install -g bower
  - bower install
script: TEST_SERVER_PORT=8090 npm test
